services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${GAZETTE_POSTGRES_DBNAME}
      POSTGRES_USER: ${GAZETTE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GAZETTE_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  ollama-init:
    image: alpine/curl
    depends_on:
      - ollama
    entrypoint: >
      sh -c "curl -s http://ollama:11434/api/pull -d '{\"model\": \"nomic-embed-text:latest\"}'"
    restart: "no"

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
      args:
        VERSION: "${GAZETTE_VERSION:-dev}"
    restart: unless-stopped
    environment:
      GAZETTE_PORT: ${GAZETTE_PORT}
      GAZETTE_SECRET_KEY: ${GAZETTE_SECRET_KEY}
      GAZETTE_POSTGRES_HOST: "postgres"
      GAZETTE_POSTGRES_USER: ${GAZETTE_POSTGRES_USER}
      GAZETTE_POSTGRES_PASSWORD: ${GAZETTE_POSTGRES_PASSWORD}
      GAZETTE_POSTGRES_DBNAME: ${GAZETTE_POSTGRES_DBNAME}
      GAZETTE_REDIS_ADDR: "redis:6379"
      GAZETTE_OAUTH_CLIENT_ID: ${GAZETTE_OAUTH_CLIENT_ID}
      GAZETTE_OAUTH_CLIENT_SECRET: ${GAZETTE_OAUTH_CLIENT_SECRET}
      GAZETTE_OAUTH_ISSUER_URL: ${GAZETTE_OAUTH_ISSUER_URL}
      GAZETTE_OAUTH_REDIRECT_URL: ${GAZETTE_OAUTH_REDIRECT_URL}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
      args:
        VERSION: "${GAZETTE_VERSION:-dev}"
    restart: unless-stopped
    environment:
      GAZETTE_POSTGRES_HOST: "postgres"
      GAZETTE_POSTGRES_USER: ${GAZETTE_POSTGRES_USER}
      GAZETTE_POSTGRES_PASSWORD: ${GAZETTE_POSTGRES_PASSWORD}
      GAZETTE_POSTGRES_DBNAME: "gazette"
      GAZETTE_REDIS_ADDR: "redis:6379"
      GAZETTE_OLLAMA_URL: "http://ollama:11434"
      GAZETTE_OLLAMA_EMBEDDINGS_MODEL: nomic-embed-text:latest
    depends_on:
      - postgres
      - redis
      - ollama-init

  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
      args:
        VERSION: "${GAZETTE_VERSION:-dev}"
    restart: unless-stopped
    environment:
      GAZETTE_REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
