version: "3"

vars:
  name: gazette

tasks:
  build-image:
    desc: Build Docker image for the given app
    vars:
      app: '{{.app | default "server"}}'
    preconditions:
      - sh: '[ "{{.app}}" = "server" ] || [ "{{.app}}" = "worker" ] || [ "{{.app}}" = "scheduler" ]]'
        msg: "❌ Error: invalid app '{{.app}}', valid options are server, worker, or scheduler."
    cmds:
      - |
        docker build \
         -f docker/{{.app}}/Dockerfile \
         -t {{.name}}-{{.app}} \
         .
    dir: ./
