// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	gofeed "github.com/mmcdole/gofeed"
	typeext "github.com/rhajizada/gazette/internal/typeext"
)

const countItemsByFeedID = `-- name: CountItemsByFeedID :one
SELECT COUNT(*) AS count
FROM items
WHERE feed_id = $1
`

func (q *Queries) CountItemsByFeedID(ctx context.Context, feedID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByFeedID, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLikedItems = `-- name: CountLikedItems :one
SELECT
  COUNT(*) AS count
FROM user_likes
WHERE user_id = $1
`

func (q *Queries) CountLikedItems(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikedItems, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSimilarItemsByItemID = `-- name: CountSimilarItemsByItemID :one
SELECT COUNT(*) AS similar_count
FROM (
  SELECT
    e.item_id
  FROM item_embeddings ie
  JOIN item_embeddings e
    ON e.item_id <> ie.item_id
  WHERE ie.item_id = $1
  GROUP BY e.item_id
  HAVING MIN(e.embedding <#> ie.embedding) <= 0.15
) AS sims
`

func (q *Queries) CountSimilarItemsByItemID(ctx context.Context, itemID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSimilarItemsByItemID, itemID)
	var similar_count int64
	err := row.Scan(&similar_count)
	return similar_count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items
  (feed_id, title, description, content, link, links, updated_parsed, published_parsed,
   authors, guid, image, categories, enclosures)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8,
   $9, $10, $11, $12, $13)
RETURNING
  id, feed_id, title, description, content, link, links, updated_parsed, published_parsed,
  authors, guid, image, categories, enclosures, created_at, updated_at
`

type CreateItemParams struct {
	FeedID          uuid.UUID          `json:"feedId"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Content         *string            `json:"content"`
	Link            string             `json:"link"`
	Links           []string           `json:"links"`
	UpdatedParsed   *time.Time         `json:"updatedParsed"`
	PublishedParsed *time.Time         `json:"publishedParsed"`
	Authors         typeext.Authors    `json:"authors"`
	Guid            *string            `json:"guid"`
	Image           *gofeed.Image      `json:"image"`
	Categories      []string           `json:"categories"`
	Enclosures      typeext.Enclosures `json:"enclosures"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.FeedID,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Link,
		arg.Links,
		arg.UpdatedParsed,
		arg.PublishedParsed,
		arg.Authors,
		arg.Guid,
		arg.Image,
		arg.Categories,
		arg.Enclosures,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Link,
		&i.Links,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Authors,
		&i.Guid,
		&i.Image,
		&i.Categories,
		&i.Enclosures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemByID = `-- name: DeleteItemByID :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItemByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemByID, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT
  id, feed_id, title, description, content, link, links, updated_parsed, published_parsed,
  authors, guid, image, categories, enclosures, created_at, updated_at
FROM items
WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Link,
		&i.Links,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Authors,
		&i.Guid,
		&i.Image,
		&i.Categories,
		&i.Enclosures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastItem = `-- name: GetLastItem :one
SELECT
  id, feed_id, title, description, content, link, links,
  updated_parsed, published_parsed, authors, guid, image,
  categories, enclosures, created_at, updated_at
FROM items
WHERE feed_id = $1
ORDER BY published_parsed DESC
LIMIT 1
`

func (q *Queries) GetLastItem(ctx context.Context, feedID uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getLastItem, feedID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Link,
		&i.Links,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Authors,
		&i.Guid,
		&i.Image,
		&i.Categories,
		&i.Enclosures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsByFeedID = `-- name: ListItemsByFeedID :many
SELECT
  id, feed_id, title, description, content, link, links, updated_parsed, published_parsed,
  authors, guid, image, categories, enclosures, created_at, updated_at
FROM items
WHERE feed_id = $1
ORDER BY published_parsed DESC
LIMIT  $2
OFFSET $3
`

type ListItemsByFeedIDParams struct {
	FeedID uuid.UUID `json:"feedId"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListItemsByFeedID(ctx context.Context, arg ListItemsByFeedIDParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByFeedID, arg.FeedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Links,
			&i.UpdatedParsed,
			&i.PublishedParsed,
			&i.Authors,
			&i.Guid,
			&i.Image,
			&i.Categories,
			&i.Enclosures,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByFeedIDForUser = `-- name: ListItemsByFeedIDForUser :many
SELECT
  i.id,
  i.feed_id,
  i.title,
  i.description,
  i.content,
  i.link,
  i.links,
  i.updated_parsed,
  i.published_parsed,
  i.authors,
  i.guid,
  i.image,
  i.categories,
  i.enclosures,
  i.created_at,
  i.updated_at,
  (ul.user_id IS NOT NULL)        AS liked,
  ul.liked_at
FROM items i
LEFT JOIN user_likes ul
  ON ul.item_id = i.id
  AND ul.user_id = $2
WHERE i.feed_id = $1
ORDER BY i.published_parsed DESC
LIMIT  $3
OFFSET $4
`

type ListItemsByFeedIDForUserParams struct {
	FeedID uuid.UUID `json:"feedId"`
	UserID uuid.UUID `json:"userId"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListItemsByFeedIDForUserRow struct {
	ID              uuid.UUID          `json:"id"`
	FeedID          uuid.UUID          `json:"feedId"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Content         *string            `json:"content"`
	Link            string             `json:"link"`
	Links           []string           `json:"links"`
	UpdatedParsed   *time.Time         `json:"updatedParsed"`
	PublishedParsed *time.Time         `json:"publishedParsed"`
	Authors         typeext.Authors    `json:"authors"`
	Guid            *string            `json:"guid"`
	Image           *gofeed.Image      `json:"image"`
	Categories      []string           `json:"categories"`
	Enclosures      typeext.Enclosures `json:"enclosures"`
	CreatedAt       time.Time          `json:"createdAt"`
	UpdatedAt       time.Time          `json:"updatedAt"`
	Liked           interface{}        `json:"liked"`
	LikedAt         *time.Time         `json:"likedAt"`
}

func (q *Queries) ListItemsByFeedIDForUser(ctx context.Context, arg ListItemsByFeedIDForUserParams) ([]ListItemsByFeedIDForUserRow, error) {
	rows, err := q.db.Query(ctx, listItemsByFeedIDForUser,
		arg.FeedID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByFeedIDForUserRow
	for rows.Next() {
		var i ListItemsByFeedIDForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Links,
			&i.UpdatedParsed,
			&i.PublishedParsed,
			&i.Authors,
			&i.Guid,
			&i.Image,
			&i.Categories,
			&i.Enclosures,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarItemsByItemIDForUser = `-- name: ListSimilarItemsByItemIDForUser :many
SELECT
  it.id,
  it.feed_id,
  it.title,
  it.description,
  it.content,
  it.link,
  it.links,
  it.updated_parsed,
  it.published_parsed,
  it.authors,
  it.guid,
  it.image,
  it.categories,
  it.enclosures,
  it.created_at,
  it.updated_at,
  (ul.user_id IS NOT NULL) AS liked,
  ul.liked_at
FROM (
  SELECT
    e.item_id
  FROM item_embeddings ie
  JOIN item_embeddings e
    ON e.item_id <> ie.item_id
  WHERE ie.item_id = $1
  GROUP BY e.item_id
  HAVING MIN(e.embedding <#> ie.embedding) <= 0.15
  ORDER BY MIN(e.embedding <#> ie.embedding) ASC
  LIMIT  $3
  OFFSET $4
) AS sims
JOIN items it
  ON it.id = sims.item_id
LEFT JOIN user_likes ul
  ON ul.user_id = $2
  AND ul.item_id = it.id
`

type ListSimilarItemsByItemIDForUserParams struct {
	ItemID uuid.UUID `json:"itemId"`
	UserID uuid.UUID `json:"userId"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListSimilarItemsByItemIDForUserRow struct {
	ID              uuid.UUID          `json:"id"`
	FeedID          uuid.UUID          `json:"feedId"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Content         *string            `json:"content"`
	Link            string             `json:"link"`
	Links           []string           `json:"links"`
	UpdatedParsed   *time.Time         `json:"updatedParsed"`
	PublishedParsed *time.Time         `json:"publishedParsed"`
	Authors         typeext.Authors    `json:"authors"`
	Guid            *string            `json:"guid"`
	Image           *gofeed.Image      `json:"image"`
	Categories      []string           `json:"categories"`
	Enclosures      typeext.Enclosures `json:"enclosures"`
	CreatedAt       time.Time          `json:"createdAt"`
	UpdatedAt       time.Time          `json:"updatedAt"`
	Liked           interface{}        `json:"liked"`
	LikedAt         *time.Time         `json:"likedAt"`
}

func (q *Queries) ListSimilarItemsByItemIDForUser(ctx context.Context, arg ListSimilarItemsByItemIDForUserParams) ([]ListSimilarItemsByItemIDForUserRow, error) {
	rows, err := q.db.Query(ctx, listSimilarItemsByItemIDForUser,
		arg.ItemID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSimilarItemsByItemIDForUserRow
	for rows.Next() {
		var i ListSimilarItemsByItemIDForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Links,
			&i.UpdatedParsed,
			&i.PublishedParsed,
			&i.Authors,
			&i.Guid,
			&i.Image,
			&i.Categories,
			&i.Enclosures,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLikedItems = `-- name: ListUserLikedItems :many
SELECT
  i.id,
  i.feed_id,
  i.title,
  i.description,
  i.content,
  i.link,
  i.links,
  i.updated_parsed,
  i.published_parsed,
  i.authors,
  i.guid,
  i.image,
  i.categories,
  i.enclosures,
  i.created_at,
  i.updated_at,
  TRUE        AS liked,
  ul.liked_at
FROM items i
JOIN user_likes ul
  ON ul.item_id = i.id
  AND ul.user_id = $1
ORDER BY ul.liked_at DESC
LIMIT  $2
OFFSET $3
`

type ListUserLikedItemsParams struct {
	UserID uuid.UUID `json:"userId"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListUserLikedItemsRow struct {
	ID              uuid.UUID          `json:"id"`
	FeedID          uuid.UUID          `json:"feedId"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Content         *string            `json:"content"`
	Link            string             `json:"link"`
	Links           []string           `json:"links"`
	UpdatedParsed   *time.Time         `json:"updatedParsed"`
	PublishedParsed *time.Time         `json:"publishedParsed"`
	Authors         typeext.Authors    `json:"authors"`
	Guid            *string            `json:"guid"`
	Image           *gofeed.Image      `json:"image"`
	Categories      []string           `json:"categories"`
	Enclosures      typeext.Enclosures `json:"enclosures"`
	CreatedAt       time.Time          `json:"createdAt"`
	UpdatedAt       time.Time          `json:"updatedAt"`
	Liked           bool               `json:"liked"`
	LikedAt         time.Time          `json:"likedAt"`
}

func (q *Queries) ListUserLikedItems(ctx context.Context, arg ListUserLikedItemsParams) ([]ListUserLikedItemsRow, error) {
	rows, err := q.db.Query(ctx, listUserLikedItems, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserLikedItemsRow
	for rows.Next() {
		var i ListUserLikedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Links,
			&i.UpdatedParsed,
			&i.PublishedParsed,
			&i.Authors,
			&i.Guid,
			&i.Image,
			&i.Categories,
			&i.Enclosures,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemByID = `-- name: UpdateItemByID :one
UPDATE items
SET
  title            = $2,
  description      = $3,
  content          = $4,
  link             = $5,
  links            = $6,
  updated_parsed   = $7,
  published_parsed = $8,
  authors          = $9,
  guid             = $10,
  image            = $11,
  categories       = $12,
  enclosures       = $13,
  updated_at       = now()
WHERE id = $1
RETURNING
  id, feed_id, title, description, content, link, links, updated_parsed, published_parsed,
  authors, guid, image, categories, enclosures, created_at, updated_at
`

type UpdateItemByIDParams struct {
	ID              uuid.UUID          `json:"id"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Content         *string            `json:"content"`
	Link            string             `json:"link"`
	Links           []string           `json:"links"`
	UpdatedParsed   *time.Time         `json:"updatedParsed"`
	PublishedParsed *time.Time         `json:"publishedParsed"`
	Authors         typeext.Authors    `json:"authors"`
	Guid            *string            `json:"guid"`
	Image           *gofeed.Image      `json:"image"`
	Categories      []string           `json:"categories"`
	Enclosures      typeext.Enclosures `json:"enclosures"`
}

func (q *Queries) UpdateItemByID(ctx context.Context, arg UpdateItemByIDParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemByID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Link,
		arg.Links,
		arg.UpdatedParsed,
		arg.PublishedParsed,
		arg.Authors,
		arg.Guid,
		arg.Image,
		arg.Categories,
		arg.Enclosures,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Link,
		&i.Links,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Authors,
		&i.Guid,
		&i.Image,
		&i.Categories,
		&i.Enclosures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
