// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
	gofeed "github.com/mmcdole/gofeed"
	typeext "github.com/rhajizada/gazette/internal/typeext"
)

type Feed struct {
	ID              uuid.UUID       `json:"id"`
	Title           *string         `json:"title"`
	Description     *string         `json:"description"`
	Link            *string         `json:"link"`
	FeedLink        string          `json:"feedLink"`
	Links           []string        `json:"links"`
	UpdatedParsed   *time.Time      `json:"updatedParsed"`
	PublishedParsed *time.Time      `json:"publishedParsed"`
	Authors         typeext.Authors `json:"authors"`
	Language        *string         `json:"language"`
	Image           *gofeed.Image   `json:"image"`
	Copyright       *string         `json:"copyright"`
	Generator       *string         `json:"generator"`
	Categories      []string        `json:"categories"`
	FeedType        *string         `json:"feedType"`
	FeedVersion     *string         `json:"feedVersion"`
	CreatedAt       time.Time       `json:"createdAt"`
	LastUpdatedAt   time.Time       `json:"lastUpdatedAt"`
}

type Item struct {
	ID              uuid.UUID          `json:"id"`
	FeedID          uuid.UUID          `json:"feedId"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Content         *string            `json:"content"`
	Link            string             `json:"link"`
	Links           []string           `json:"links"`
	UpdatedParsed   *time.Time         `json:"updatedParsed"`
	PublishedParsed *time.Time         `json:"publishedParsed"`
	Authors         typeext.Authors    `json:"authors"`
	Guid            *string            `json:"guid"`
	Image           *gofeed.Image      `json:"image"`
	Categories      []string           `json:"categories"`
	Enclosures      typeext.Enclosures `json:"enclosures"`
	CreatedAt       time.Time          `json:"createdAt"`
	UpdatedAt       time.Time          `json:"updatedAt"`
}
