// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	DeleteFeedByID(ctx context.Context, id uuid.UUID) error
	DeleteItemByID(ctx context.Context, id uuid.UUID) error
	GetFeedByID(ctx context.Context, id uuid.UUID) (Feed, error)
	GetItemByID(ctx context.Context, id uuid.UUID) (Item, error)
	GetLastItem(ctx context.Context, feedID uuid.UUID) (Item, error)
	ListFeeds(ctx context.Context, arg ListFeedsParams) ([]Feed, error)
	ListItemsByFeedID(ctx context.Context, arg ListItemsByFeedIDParams) ([]Item, error)
	UpdateFeedByID(ctx context.Context, arg UpdateFeedByIDParams) (Feed, error)
	UpdateItemByID(ctx context.Context, arg UpdateItemByIDParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
