name: Build '${{ inputs.app }}' image

on:
  workflow_call:
    inputs:
      app:
        description: "App to build and push to the registry (e.g server, worker or scheduler)"
        required: true
        type: string
      tag:
        description: "Image tag"
        required: true
        type: string
      push:
        description: "Push image to the registry"
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/${{ inputs.app }}
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ github.repository }}/${{ inputs.app }}:${{ inputs.tag }}
