name: Push images

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.image-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set image tag
        id: image-tag
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          fi

  push-images:
    needs: image-tag
    strategy:
      matrix:
        app: [server, worker, scheduler]
    uses: ./.gitea/workflows/build-image.yml
    secrets: inherit
    with:
      app: ${{ matrix.app }}
      tag: ${{ needs.image-tag.outputs.tag }}
      push: true
